apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-runner-secrets-reader-binding
  namespace: gitlab-runner
subjects:
- kind: ServiceAccount
  name: default
  namespace: gitlab-runner
roleRef:
  kind: Role
  name: gitlab-runner-secrets-reader
  apiGroup: rbac.authorization.k8s.io
