stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/mikhailde/my-app
  DOCKER_HOST: tcp://docker-dind:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:dind
    alias: docker-dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  image: docker:latest
  script:
    - export DOCKER_HOST=tcp://docker-dind:2375
    - docker build -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest

test:
  stage: test
  image: python:latest
  script:
    - pip install -r requirements.txt
    - python -m unittest discover -s tests

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - helm upgrade --install my-app ./chart --set image.tag=latest --set image.repository=$IMAGE_NAME