stages:
  - build
  - test
  - deploy

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --destination "${CI_REGISTRY_IMAGE}:latest"

test_endpoints:
  stage: test
  image: python:latest
  script:
    - pip install -r requirements.txt
    - python -m unittest discover test_app.TestEndpoints
  parallel: 2

test_utils:
  stage: test
  image: python:latest
  script:
    - pip install -r requirements.txt
    - python -m unittests discover test_app.TestUtils
  parallel: 2

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - helm upgrade --install my-app ./chart --set image.tag=latest --set image.repository=$CI_REGISTRY_IMAGE --namespace my-app --create-namespace
    - kubectl rollout restart deployment my-app -n my-app
