stages:
  - test
  - deploy

test:
  stage: test
  image: python:latest
  script:
    - pip install -r requirements.txt
    - python -m unittest discover -s tests

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - helm upgrade --install my-app ./chart