stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/$CI_REGISTRY_USER/my-app

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker context use minikube
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest

test:
  stage: test
  image: python:latest
  script:
    - pip install -r requirements.txt
    - python -m unittest discover -s tests

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - helm upgrade --install my-app ./chart --set image.tag=latest --set image.repository=$IMAGE_NAME