stages:
  - build
  - test
  - deploy

variables:
  DOCKER_HOST: host.minikube.internal:2375
  
build:
  stage: build
  image: docker:latest
  script:
    - docker login -u $GITLAB_USER_LOGIN -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest

test:
  stage: test
  image: python:latest
  script:
    - pip install -r requirements.txt
    - python -m unittest discover -s tests

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - helm upgrade --install my-app ./chart --set image.tag=latest --set image.repository=$CI_REGISTRY_IMAGE --namespace my-app --create-namespace