stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/mikhailde/my-app

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  image: gcr.io/kaniko-project/executor:latest
  script:
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $IMAGE_NAME:latest

test:
  stage: test
  image: python:3.9
  script:
    - pip install -r requirements.txt
    - python -m unittest discover -s tests

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - helm upgrade --install my-app ./chart --set image.tag=latest --set image.repository=$IMAGE_NAME