stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip
    - venv/

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install --no-cache-dir -r requirements.txt
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr-d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context "${CI_PROJECT_DIR}" --dockerfile "${CI_PROJECT_DIR}/Dockerfile" --destination "${IMAGE_NAME}:latest"
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - venv/
  artifacts:
    paths:
      - venv/

test_util_1:
  stage: test
  image: python:latest
  script:
    - source venv/bin/activate
    - python -m unittest tests.test_app.TestUtil1
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - venv/
  dependencies:
    - build

test_util_2:
  stage: test
  image: python:latest
  script:
    - source venv/bin/activate
    - python -m unittest tests.test_app.TestUtil2
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - venv/
  dependencies:
    - build

test_flask_app:
  stage: test
  image: python:latest
  script:
    - python -m unittest tests.test_app.TestFlaskApp
    - source venv/bin/activate
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - venv/
  dependencies:
    - build

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - helm upgrade --install my-app ./chart --set image.tag=latest --set image.repository=$CI_REGISTRY_IMAGE --namespace my-app --create-namespace
    - kubectl rollout restart deployment my-app -n my-app
