stages:
  - build
  - test
  - deploy

variables:
  IMAGE_NAME: registry.gitlab.com/mikhailde/my-app

build:
  stage: build
  image: gcr.io/kaniko-project/executor:debug
  script:
    - echo "CI_REGISTRY_USER: $CI_REGISTRY_USER"
    - echo "CI_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD"
    - echo "CI_REGISTRY: $CI_REGISTRY"
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $IMAGE_NAME:latest

test:
  stage: test
  image: python:3.9
  script:
    - pip install -r requirements.txt
    - python -m unittest discover -s tests

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - helm upgrade --install my-app ./chart --set image.tag=latest --set image.repository=$IMAGE_NAME