{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "my-app.name" . }}
{{- if .Values.serviceMonitor.namespace }}
  namespace: {{ .Release.Namespace }}
{{- end }}
  labels:
    app.kubernetes.io/name: {{ template "my-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- with .Values.serviceMonitor.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - path: /metrics
      port: metrics
      interval: 15s
      scrapeTimeout: 30s
      honorLabels: {{ .Values.serviceMonitor.honorLabels }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "my-app.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
