gitlabUrl: "https://gitlab.com/"
rbac:
  create: true
  rules:
    - apiGroups: [""]
      resources: ["*"]
      verbs: ["*"]
    - apiGroups: ["networking.k8s.io"]
      resources: ["ingresses"]
      verbs: ["*"]
    - apiGroups: ["apps"]
      resources: ["deployments"]
      verbs: ["*"]
    - apiGroups: ["flagger.app"]
      resources: ["canaries"]
      verbs: ["*"]
    - apiGroups: ["monitoring.coreos.com"]
      resources: ["servicemonitors"]
      verbs: ["*"]
    - apiGroups: ["apiextensions.k8s.io"]
      resources: ["customresourcedefinitions"]
      verbs: ["*"]
  clusterWideAccess: true
serviceAccount:
  create: true
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
service:
  enabled: true
runners:
  config: |
    [[runners]]
      [runners.kubernetes]
        image = "ubuntu:22.04"
        service_account = "gitlab-runner"
        [runners.kubernetes.volumes]
          [[runners.kubernetes.volumes.pvc]]
          name = "gitlab-cache-pvc"
          mount_path = "/cache"
          mount_propagation = "HostToContainer"
        [runners.kubernetes.cache]
          Type = "persistentVolumeClaim"
          Shared = true
          Path = "/cache"

  secret: gitlab-runner-secret
