grafana:
  service:
    type: NodePort
  alertmanager:
    handleGrafanaManagedAlerts: true

prometheus:
  service:
    type: NodePort
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
