{
 "title": "GitLab CI/CD",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Количество активных runner'ов",
   "type": "stat",
   "description": "Отображает количество GitLab runner'ов, которые в данный момент активны и могут выполнять задания CI/CD.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count_values(\"runner\", gitlab_runner_jobs{state=\"running\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Обзор состояния раннеров",
   "type": "gauge",
   "description": "Количество выполняемых заданий на каждом раннере.",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Jobs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gitlab_runner_jobs) by (runner)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ошибки Runner'ов",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gitlab_runner_errors_total) by (level)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Использование CPU runner'ом (%)",
   "type": "timeseries",
   "description": "Отображает процент использования CPU процессом GitLab Runner за последние 5 минут.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "100 * rate(process_cpu_seconds_total{job=\"gitlab-runner\"}[5m]) / 2",
     "legendFormat": "{{instance}} - {{job}}"
    }
   ]
  },
  {
   "title": "Среднее время выполнения заданий",
   "type": "timeseries",
   "description": "График отображает среднее время выполнения заданий CI/CD для каждого GitLab Runner за последние 5 минут.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (runner, system_id, instance, job, namespace, pod, service, container, endpoint) (rate(gitlab_runner_job_duration_seconds_sum[5m])) / rate(gitlab_runner_job_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Скорость изменения bucket'ов времени ожидания в очереди",
   "type": "timeseries",
   "description": "График отображает скорость изменения значений в bucket'ах гистограммы времени ожидания заданий в очереди GitLab Runner за последние 5 минут. Каждый bucket представляет временной интервал ожидания.",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(gitlab_runner_job_queue_duration_seconds_bucket[5m])",
     "legendFormat": " {{le}}"
    }
   ]
  },
  {
   "title": "Использование памяти runner'ом",
   "type": "timeseries",
   "description": "Отображает текущий объем используемой памяти процессом GitLab Runner.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"gitlab-runner\"}",
     "legendFormat": "{{instance}} - {{job}}"
    }
   ]
  }
 ]
}