{
 "title": "GitLab CI/CD",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Использование CPU runner'ом",
   "type": "timeseries",
   "description": "Отображает процент использования CPU процессом GitLab Runner.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "100 * rate(process_cpu_seconds_total{job=\"gitlab-runner\"}[5m]) / 2",
     "legendFormat": "{{instance}} - {{job}}"
    }
   ]
  },
  {
   "title": "Количество активных runner'ов",
   "type": "stat",
   "description": "Отображает количество GitLab runner'ов, которые в данный момент активны и могут выполнять задания CI/CD.",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count_values(\"runner\", gitlab_runner_jobs{state=\"running\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Обзор состояния раннеров",
   "type": "gauge",
   "description": "Количество выполняемых заданий на каждом раннере.",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Jobs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gitlab_runner_jobs) by (runner)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ошибки Runner'ов",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gitlab_runner_errors_total) by (level)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Использование памяти runner'ом",
   "type": "timeseries",
   "description": "Процент использования резидентной памяти runner'ом",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(process_resident_memory_bytes{job=\"gitlab-runner\"} / 3455541248) * 100",
     "legendFormat": "{{instance}} - {{job}}"
    }
   ]
  },
  {
   "title": "Средняя продолжительность заданий",
   "type": "stat",
   "description": "Этот индикатор отображает среднюю продолжительность заданий",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(gitlab_runner_job_duration_seconds_sum[5m])) / avg(rate(gitlab_runner_job_duration_seconds_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее время ожидания в очереди",
   "type": "stat",
   "description": "Среднее время, которое задачи проводят в очереди до начала выполнения.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(gitlab_runner_job_queue_duration_seconds_sum{project_jobs_running=\"+Inf\"} / gitlab_runner_job_queue_duration_seconds_count{project_jobs_running=\"+Inf\"}) by (runner)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}