{
 "title": "Обзор производительности приложения",
 "description": " Этот дашборд предоставляет обзор ключевых метрик производительности приложения, включая использование ресурсов (CPU, память), время отклика запросов, а также информацию о сборщике мусора Python. Он предназначен для быстрого обнаружения потенциальных проблем и узких мест в производительности.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Использование CPU (my-app)",
   "type": "timeseries",
   "description": "Мониторинг использования CPU приложением my-app для выявления высокой нагрузки, узких мест и потенциальных проблем с производительностью.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job=\"my-app\"}[1m])) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потребление памяти my-app",
   "type": "timeseries",
   "description": "Отображать текущее и историческое потребление резидентной памяти сервисом my-app, позволяя быстро обнаружить аномалии и потенциальные проблемы с нехваткой памяти.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(process_resident_memory_bytes{job=\"my-app\"}) / sum(node_memory_MemTotal_bytes) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Сборки мусора (my-app)",
   "type": "timeseries",
   "description": "Мониторинг частоты сборок мусора (GC) для приложения my-app, с целью выявления потенциальных проблем с управлением памятью и производительностью.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(python_gc_collections_total{job=\"my-app\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время обработки запросов (my-app)",
   "type": "timeseries",
   "description": "Визуализировать среднее время обработки запросов к различным endpoint'ам приложения my-app за определенный период, обнаруживать аномалии и выявлять узкие места производительности.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (exported_endpoint) (rate(request_latency_seconds_sum{job=\"my-app\"}[1m])) / sum by (exported_endpoint) (rate(request_latency_seconds_count{job=\"my-app\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}