apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-cache-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/vda1/hostpath_pv
